# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-homehaven"
BBFILE_PATTERN_meta-homehaven = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-homehaven = "6"

LAYERDEPENDS_meta-homehaven = "core"
LAYERSERIES_COMPAT_meta-homehaven = "walnascar"
